export const SUCCESS_FAILURE = {
  REQUESTED: "SUCCESS_FAILURE_REQUESTED",
  FETCHED: "SUCCESS_FAILURE_FETCHED",
  ERROR: "SUCCESS_FAILURE_ERROR",
  UPDATE: "SUCCESS_FAILURE_UPDATE",
};
export const TIMESTAMP_SUCCESS_FAILURE = {
  REQUESTED: "TIMESTAMP_SUCCESS_FAILURE_REQUESTED",
  FETCHED: "TIMESTAMP_SUCCESS_FAILURE_FETCHED",
  ERROR: "TIMESTAMP_SUCCESS_FAILURE_ERROR",
  UPDATE: "TIMESTAMP_SUCCESS_FAILURE_UPDATE",
};
export const USER_SUCCESS_FAILURE = {
  REQUESTED: "USER_SUCCESS_FAILURE_REQUESTED",
  FETCHED: "USER_SUCCESS_FAILURE_FETCHED",
  ERROR: "USER_SUCCESS_FAILURE_ERROR",
  UPDATE: "USER_SUCCESS_FAILURE_UPDATE",
};
